annie = User.create(username: "annie", password: "annie")

User.create([{username: 'peggy', password: 'peggy'}, {username: 'joe', password: 'joe'}])

room_1 = Room.create([{name: "Bathroom"}])
room_2 = Room.create([{name: "Master Bedroom"}])
room_3 = Room.create([{name: "Kitchen"}])
room_4 = Room.create([{name: "Sunroom"}])
room_5 = Room.create([{name: "Dining Room"}])
room_6 = Room.create([{name: "Living Room"}])
room_7 = Room.create([{name: "Guest Bedroom"}])
room_8 = Room.create([{name: "Foyer"}])
room_10 = Room.create([{name: "Game Room"}])
room_11 = Room.create([{name: "Office"}])
room_12 = Room.create([{name: "Library"}])
room_13 = Room.create([{name: "Gym"}])